server:
  port: 8082

spring:
  application:
    name: order-service
  redis:
    host: localhost
    port: 6379
    database: 0

# Sa-Token 配置
sa-token:
  token-name: satoken
  timeout: 2592000
  token-style: uuid
  is-log: true
